### ISSUE TITLE
Add core developers to npmjs

### ISSUE THREAD

**Issue by blahah** [slidewinder/direction#4]

**Comment by blahah** [comment]
@Ward9250 I've added the npmjs user `ward9250` as a collaborator. Assuming that's you?

Can you confirm you're appearing as a collaborator here: https://www.npmjs.com/package/slidewinder

And then close this issue?

**Comment by TransGirlCodes** [comment]
That's me - it says on my npm profile I have 1 package, and that's slidewinder. :)
